### ISSUE TITLE
Define acceptance test for creating and modify user profile

### ISSUE THREAD

**Issue by RancyKaur** [RancyKaur/Brainstorm-Soen6011summer2023#12]
**User Story Link:** https://github.com/RancyKaur/Brainstorm-Soen6011summer2023/issues/4

**Task Title:** Define acceptance test for creating and modify user profile

**Description:**
Write acceptance test to validate creation and modification of user profile for both candidate and employer

**Comment by ronakjpatel** [comment]
Done attached in pdf testcases.pdf
