### ISSUE TITLE
Design and code New User Profile page

### ISSUE THREAD

**Issue by RancyKaur** [RancyKaur/Brainstorm-Soen6011summer2023#13]
**User Story Link**: https://github.com/RancyKaur/Brainstorm-Soen6011summer2023/issues/4

**Task Title**: Design and code New User Profile page

**Description:**
First Design user profile page for candidate and user profile page for employer
Code creation of new user profile page

**Comment by PreetAngadSingh** [comment]
Closing this issue, resolved it with #60
