### ISSUE TITLE
Code build resume page

### ISSUE THREAD

**Issue by RancyKaur** [RancyKaur/Brainstorm-Soen6011summer2023#16]
**User Story Link:** https://github.com/RancyKaur/Brainstorm-Soen6011summer2023/issues/4

**Task Title**: Code Code build resume page

**Description:**
Create feature for building resume that candidate can use to input information about themselves to apply for jobs
The information such as qualification, job experience, skills etc.

**Comment by ronakjpatel** [comment]
Successfully added the feature against pull request [link](https://github.com/RancyKaur/Brainstorm-Soen6011summer2023/pull/64)
