### ISSUE TITLE
Define acceptance test for adding and managing job postings

### ISSUE THREAD

**Issue by ronakjpatel** [RancyKaur/Brainstorm-Soen6011summer2023#39]
User Story Link https://github.com/RancyKaur/Brainstorm-Soen6011summer2023/issues/7

Task Title : Define acceptance test for adding and managing job postings

**Comment by RancyKaur** [comment]
Test cases are updated in test.pdf

**Comment by RancyKaur** [comment]
Test cases are updated in test.pdf
