### ISSUE TITLE
Create Sign Up page for employer and candidates

### ISSUE THREAD

**Issue by RancyKaur** [RancyKaur/Brainstorm-Soen6011summer2023#5]
**User Story Link**: https://github.com/RancyKaur/Brainstorm-Soen6011summer2023/issues/4

**Task Title**: Create Sign Up page for employer and Student/Candidate

**Description:**
New user can sign up/register to create their accounts as student/candidate or employer
Sign up page can ask for basic information such as First Name, Last Name, Email address, Phone Number, Gender, UserName, Password and Role (Candidate/Employer)
Once the user signs up, this information is saved in the application

**Comment by prabhjot023** [comment]
Done . Pull request #54
