### ISSUE TITLE
Create login page for employer and candidate

### ISSUE THREAD

**Issue by RancyKaur** [RancyKaur/Brainstorm-Soen6011summer2023#6]
**User Story Link**: https://github.com/RancyKaur/Brainstorm-Soen6011summer2023/issues/4

**Task Title:** Create Login page for employer and Student/Candidate

**Description:**
Login page with UserName and Password inputs
We can also include Role, need to think about it
When they login, they would see the page as per their role

**Comment by prabhjot023** [comment]
It has been done . Pull request #54
